# K-Means Clustering

## Objective

To segment customers into 5 clusters using the K-Means clustering algorithm based on scaled Annual Income and Spending Score.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.cluster import KMeans

In [2]:
X_scaled = pd.read_csv("../data/scaled_customer_data.csv")

In [3]:
X_scaled

     Annual Income (k$)  Spending Score (1-100)
0             -1.738999               -0.434801
1             -1.738999                1.195704
2             -1.700830               -1.715913
3             -1.700830                1.040418
4             -1.662660               -0.395980
..                  ...                     ...
195            2.268791                1.118061
196            2.497807               -0.861839
197            2.497807                0.923953
198            2.917671               -1.250054
199            2.917671                1.273347

[200 rows x 2 columns]

In [4]:
X_scaled.head()

   Annual Income (k$)  Spending Score (1-100)
0           -1.738999               -0.434801
1           -1.738999                1.195704
2           -1.700830               -1.715913
3           -1.700830                1.040418
4           -1.662660               -0.395980

In [5]:
X_scaled.shape

(200, 2)

In [6]:
X_scaled.columns

Index(['Annual Income (k$)', 'Spending Score (1-100)'], dtype='str')

In [7]:
X = X_scaled.values

In [8]:
X[:5]

array([[-1.73899919, -0.43480148],
       [-1.73899919,  1.19570407],
       [-1.70082976, -1.71591298],
       [-1.70082976,  1.04041783],
       [-1.66266033, -0.39597992]])

In [9]:
kmeans = KMeans(
    n_clusters=5,
    random_state=42,
    n_init=10
)

In [10]:
kmeans.fit(X)

KMeans(n_clusters=5, n_init=10, random_state=42)

In [11]:
labels = kmeans.labels_

In [12]:
labels[:10]

array([4, 2, 4, 2, 4, 2, 4, 2, 4, 2], dtype=int32)

In [13]:
df = pd.read_csv("../data/raw/Mall_Customers.csv")

In [14]:
df.head()

   CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [15]:
df["Cluster"] = labels

In [16]:
df.head()

,CustomerID,Gender,Age,Annual Income (k$),Spending Score (1-100),Cluster
0,1,Male,19,15,39,4
1,2,Male,21,15,81,2
2,3,Female,20,16,6,4
3,4,Female,23,16,77,2
4,5,Female,31,17,40,4

In [17]:
df["Cluster"].value_counts().sort_index()

Cluster
0    81
1    39
2    22
3    35
4    23
Name: count, dtype: int64

In [18]:
df.to_csv(
    "../data/customer_segments.csv",
    index=False
)

In [19]:
df["Cluster"].value_counts().sort_index()

Cluster
0    81
1    39
2    22
3    35
4    23
Name: count, dtype: int64